name: BSseq
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - _r-mutex=1.0.1
  - appdirs=1.4.3
  - attrs=19.3.0
  - bedtools=2.29.0
  - bioconductor-annotate=1.64.0
  - bioconductor-annotationdbi=1.48.0
  - bioconductor-annotationhub=2.18.0
  - bioconductor-annotatr=1.12.0
  - bioconductor-beachmat=2.2.0
  - bioconductor-biobase=2.46.0
  - bioconductor-biocfilecache=1.10.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biocparallel=1.20.0
  - bioconductor-biocversion=3.10.1
  - bioconductor-biomart=2.42.0
  - bioconductor-biostrings=2.54.0
  - bioconductor-bsgenome=1.54.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg19=1.4.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.1
  - bioconductor-bsseq=1.22.0
  - bioconductor-bumphunter=1.28.0
  - bioconductor-delayedarray=0.12.0
  - bioconductor-delayedmatrixstats=1.8.0
  - bioconductor-dmrseq=1.6.0
  - bioconductor-genefilter=1.68.0
  - bioconductor-genomeinfodb=1.22.0
  - bioconductor-genomeinfodbdata=1.2.2
  - bioconductor-genomicalignments=1.22.0
  - bioconductor-genomicfeatures=1.38.0
  - bioconductor-genomicranges=1.38.0
  - bioconductor-geoquery=2.54.0
  - bioconductor-hdf5array=1.14.0
  - bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19=0.6.0
  - bioconductor-illuminahumanmethylation450kmanifest=0.4.0
  - bioconductor-illuminahumanmethylationepicanno.ilm10b4.hg19=0.6.0
  - bioconductor-illuminahumanmethylationepicmanifest=0.3.0
  - bioconductor-illuminaio=0.28.0
  - bioconductor-interactivedisplaybase=1.24.0
  - bioconductor-iranges=2.20.0
  - bioconductor-limma=3.42.0
  - bioconductor-minfi=1.32.0
  - bioconductor-multtest=2.42.0
  - bioconductor-preprocesscore=1.48.0
  - bioconductor-regioner=1.18.0
  - bioconductor-rhdf5=2.30.0
  - bioconductor-rhdf5lib=1.8.0
  - bioconductor-rhtslib=1.18.0
  - bioconductor-rsamtools=2.2.0
  - bioconductor-rtracklayer=1.46.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-siggenes=1.60.0
  - bioconductor-summarizedexperiment=1.16.0
  - bioconductor-xvector=0.26.0
  - bioconductor-zlibbioc=1.32.0
  - bismark=0.22.3
  - bowtie2=2.3.5
  - bwidget=1.9.13
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - cctools=927.0.2
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - clang=9.0.0
  - clang_osx-64=9.0.0
  - clangxx=9.0.0
  - clangxx_osx-64=9.0.0
  - click=7.0
  - coloredlogs=10.0
  - colormath=3.0.0
  - compiler-rt=9.0.0
  - compiler-rt_osx-64=9.0.0
  - configargparse=0.13.0
  - cryptography=2.8
  - curl=7.65.3
  - cutadapt=2.7
  - cycler=0.10.0
  - datrie=0.8
  - decorator=4.4.1
  - dnaio=0.4.1
  - docutils=0.15.2
  - fastqc=0.11.8
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.13.1
  - freetype=2.10.0
  - fribidi=1.0.5
  - future=0.18.2
  - gettext=0.19.8.1
  - gfortran_impl_osx-64=7.3.0
  - gfortran_osx-64=7.3.0
  - gitdb2=2.0.6
  - gitpython=3.0.5
  - glib=2.58.3
  - gmp=6.1.2
  - graphite2=1.3.13
  - gsl=2.5
  - harfbuzz=2.4.0
  - hisat2=2.1.0
  - htslib=1.9
  - humanfriendly=4.18
  - icu=64.2
  - idna=2.8
  - importlib_metadata=1.1.0
  - isl=0.19
  - jinja2=2.10.3
  - jpeg=9c
  - jsonschema=3.2.0
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - ld64=450.3
  - ldc=1.13.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libcxx=9.0.0
  - libdeflate=1.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libxml2=2.9.10
  - llvm-openmp=9.0.0
  - lz4-c=1.8.3
  - lzstring=1.0.4
  - make=4.2.1
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=2.2.4
  - matplotlib-base=2.2.4
  - more-itertools=8.0.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - multiqc=1.8
  - ncurses=6.1
  - networkx=2.1
  - numpy=1.17.3
  - openjdk=11.0.1
  - openssl=1.1.1d
  - pandas=0.25.3
  - pango=1.42.4
  - pcre=8.43
  - perl=5.26.2
  - pigz=2.3.4
  - pip=19.3.1
  - pixman=0.38.0
  - psutil=5.6.7
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pyparsing=2.4.5
  - pyrsistent=0.15.6
  - pysocks=1.7.1
  - python=3.6.7
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyyaml=5.2
  - r-argparse=2.0.1
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.5
  - r-base=3.6.1
  - r-base64=2.0
  - r-beanplot=1.2
  - r-bh=1.69.0_1
  - r-bibtex=0.4.2
  - r-biocmanager=1.30.10
  - r-bit=1.1_14
  - r-bit64=0.9_7
  - r-bitops=1.0_6
  - r-blob=1.2.0
  - r-cli=1.1.0
  - r-clipr=0.7.0
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-curl=4.3
  - r-data.table=1.12.6
  - r-dbi=1.0.0
  - r-dbplyr=1.4.2
  - r-digest=0.6.23
  - r-dorng=1.7.1
  - r-dplyr=0.8.3
  - r-ellipsis=0.3.0
  - r-fansi=0.4.0
  - r-farver=2.0.1
  - r-fastmap=1.0.1
  - r-findpython=1.0.5
  - r-foreach=1.4.7
  - r-formatr=1.7
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-getopt=1.20.3
  - r-ggplot2=3.2.1
  - r-glue=1.3.1
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-gtools=3.8.1
  - r-hms=0.5.2
  - r-htmltools=0.4.0
  - r-httpuv=1.5.2
  - r-httr=1.4.1
  - r-iterators=1.0.12
  - r-jsonlite=1.6
  - r-labeling=0.3
  - r-lambda.r=1.2.4
  - r-later=1.0.0
  - r-lattice=0.20_38
  - r-lazyeval=0.2.2
  - r-lifecycle=0.1.0
  - r-locfit=1.5_9.1
  - r-magrittr=1.5
  - r-mass=7.3_51.4
  - r-matrix=1.2_17
  - r-matrixstats=0.55.0
  - r-mclust=5.4.5
  - r-memoise=1.1.0
  - r-mgcv=1.8_29
  - r-mime=0.7
  - r-munsell=0.5.0
  - r-nlme=3.1_141
  - r-nor1mix=1.3_0
  - r-openssl=1.4.1
  - r-outliers=0.14
  - r-permute=0.9_5
  - r-pheatmap=1.0.12
  - r-pillar=1.4.2
  - r-pkgconfig=2.0.3
  - r-pkgmaker=0.27
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-prettyunits=1.0.2
  - r-progress=1.2.2
  - r-promises=1.1.0
  - r-purrr=0.3.3
  - r-quadprog=1.5_7
  - r-r.methodss3=1.7.1
  - r-r.oo=1.23.0
  - r-r.utils=2.9.0
  - r-r6=2.4.1
  - r-rappdirs=0.3.1
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.3
  - r-rcurl=1.95_4.12
  - r-readr=1.3.1
  - r-registry=0.5_1
  - r-reshape=0.8.8
  - r-reshape2=1.4.3
  - r-rlang=0.4.2
  - r-rngtools=1.4
  - r-rsqlite=2.1.2
  - r-scales=1.1.0
  - r-scrime=1.3.5
  - r-shiny=1.4.0
  - r-snow=0.4_3
  - r-sourcetools=0.1.7
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - r-sys=3.3
  - r-tibble=2.1.3
  - r-tidyr=1.0.0
  - r-tidyselect=0.2.5
  - r-upsetr=1.4.0
  - r-utf8=1.1.4
  - r-vctrs=0.2.0
  - r-viridislite=0.3.0
  - r-withr=2.1.2
  - r-xml=3.98_1.20
  - r-xml2=1.2.2
  - r-xtable=1.8_4
  - r-yaml=2.2.0
  - r-zeallot=0.1.0
  - ratelimiter=1.2.0
  - readline=8.0
  - requests=2.22.0
  - sambamba=0.7.1
  - samtools=1.9
  - setuptools=42.0.2
  - simplejson=3.17.0
  - six=1.13.0
  - smmap2=2.0.5
  - snakemake-minimal=5.8.1
  - spectra=0.0.11
  - sqlite=3.30.1
  - tapi=1000.10.8
  - tbb=2019.9
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.0.3
  - trim-galore=0.6.5
  - urllib3=1.25.7
  - wheel=0.33.6
  - wrapt=1.11.2
  - xopen=0.8.4
  - xz=5.2.4
  - yaml=0.2.2
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.4
